def paramsListStart= [
    choice(
        choices: ['GSPRF','GSDEV','GSTRN','GSSIT','GSUAT','GSUQA','GSPRD'], 
        name: 'env',
        description: 'Environment to Deploy'
    )
]
def paramsListEnd= [
    choice(
        choices: ['us-east-2','us-east-1'], 
        name: 'region'
    ),
    gitParameter(
        branchFilter: 'origin/(.*)', //filtering this common part of all branch names
        defaultValue: 'master', 
        name: 'BRANCH', 
        type: 'PT_BRANCH'
    )
]

properties([
    parameters(
        paramsListStart + paramsListEnd
    )
])

pipeline {
    agent { label 'ubuntu' }
    stages {
        stage('Get Repo') {
            steps {
                script{
                    echo "Cloning Git repo..."
                }
            }
        }
        stage('Build the API'){
            steps{
                script{
                    echo "Building with maven"
                    echo "The environment is: ${params.env}"
                    echo "The region is: ${params.region}"
                    echo "The branch is: ${params.BRANCH}"
                }
            }
        }
        stage('Archive the artifact') {
            steps{
                script{
                    echo "Deployment done!" 
                }
            }
        }
    }
}